ZJIT: Load immediate into register before masking (#16677)
This otherwise causes a crash on e.g. https://github.com/ruby/ruby/pull/15220:

    thread '<unnamed>' (18071) panicked at zjit/src/codegen.rs:2511:21:
    internal error: entered unreachable code: with_num_bits should not be used for: Value(VALUE(19239180))
    stack backtrace:
       0: __rustc::rust_begin_unwind
                 at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library/std/src/panicking.rs:689:5
       1: core::panicking::panic_fmt
                 at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library/core/src/panicking.rs:80:14
       2: zjit::backend::lir::Opnd::with_num_bits
                 at /home/runner/work/ruby/ruby/src/zjit/src/backend/lir.rs:457:18
       3: zjit::codegen::gen_guard_type
                 at /home/runner/work/ruby/ruby/src/zjit/src/codegen.rs:2511:21
       4: zjit::codegen::gen_insn
                 at /home/runner/work/ruby/ruby/src/zjit/src/codegen.rs:690:55